### ISSUE TITLE
Microk8s Compatibility

### ISSUE THREAD

**Issue by sstubbs** [minio/direct-csi#11]
Hi,

I'm trying to install this on microk8s but I get the following error:
```
MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry is not a directory
```

I had a similar issue with rook using ceph which was fixed by changing the kubelet directory in the config. It would be great if there was a way to do this. I've istalled it with:
```
DIRECT_CSI_DRIVES=data{1...4} DIRECT_CSI_DRIVES_DIR=/mnt kubectl apply -k github.com/minio/direct-csi
```

**Comment by sstubbs** [comment]
rook has a variable called csi.kubeletDirPath in their helm chart to do this.

**Comment by immanuelfodor** [comment]
#14 has added the `KUBELET_DIR_PATH` variable, so you can now specify it as well, and the pods start up fine. 

Bumped into this problem following the instructions at https://github.com/minio/operator/blob/master/docs/using-direct-csi.md as it doesn't mention this variable, and got the same error as you did.

**Comment by sstubbs** [comment]
Oh I'm glad that PR got merged. I'll do a PR to update the docs and hopefully that can be merged soon so people know that it's there.

**Comment by sstubbs** [comment]
Since this commit https://github.com/minio/direct-csi/commit/82b68853260a06b33321c921ae99836fbc9c444a I can't override kubelet path. 

I'm trying it with the following:
```
DIRECT_CSI_DRIVES=minio-data{1...4} \
DIRECT_CSI_DRIVES_DIR=/mnt \
KUBELET_DIR_PATH=/var/snap/microk8s/common/var/lib/kubelet \
kubectl apply -k github.com/minio/direct-csi
```

**Comment by sstubbs** [comment]
Not a problem for me as I will just use a fork but in case anybody else has this problem you can make this change. https://github.com/sstubbs/direct-csi/commit/b26ba15fce36a1fcb2d2a4577befe4b7eb8bd5e1

**Comment by harshavardhana** [comment]
> Not a problem for me as I will just use a fork but in case anybody else has this problem you can make this change. [sstubbs@b26ba15](https://github.com/sstubbs/direct-csi/commit/b26ba15fce36a1fcb2d2a4577befe4b7eb8bd5e1)

That looks like a bit silly from kustomize point of view that it doesn't override the values from their default state and we cannot set valid default values either.

**Comment by sstubbs** [comment]
I agree. Not sure why it doesn't work but just thought I would add it here in case anybody else has issues.

**Comment by wlan0** [comment]
Closing this issue. Please reopen if you'd like to discuss further

**Comment by Berndinox** [comment]
@sstubbs - may you have a template on how you got rook running on microk8s? Thanks!

**Comment by usersina** [comment]
Also using MicroK8s here.

Is there a way to pass the value of `KUBELET_DIR_PATH` to the install command `kubectl directpv install`?

Since doing an `export` before running the command didn't cut it for me, I followed the [custom installation guide](https://github.com/minio/directpv/blob/master/docs/installation.md#custom-installation) and ultimately proceeded with:

- Generating the config yaml
```bash
kubectl directpv install --dry-run > directpv-install.yaml
```
- Updating all occurrences of `/var/lib/kubelet/` with `/var/snap/microk8s/common/var/lib/kubelet/`
- Directly applying the file instead of doing the normal `kubectl directpv install`
```
kubectl create -f directpv-install.yaml
```

There is an option for the kubeconfig `-k, --kubeconfig string` but I don't see any for the kublet directory.
