### ISSUE TITLE
Multiple Storage Classes

### ISSUE THREAD

**Issue by sstubbs** [minio/direct-csi#12]
Currently I use openebs local pvs for databases. I will be using this for minio but I am wondering is it possible to create multiple strorage classes and if so how would I do that? I would rather just use this than openebs and this so that I make things simpler.

**Comment by sstubbs** [comment]
Hi, I second issue which would be solved by this. I am adding hdds to servers which currently have ssds registered with this. It would be great if I could have two separate installations of this. One for low performance and one for high performance so I can have two different minio installations.

**Comment by sstubbs** [comment]
Would I be able to do this by deploying in different namespace or changing https://github.com/minio/direct-csi/blob/e47cddf96a4b857e02ace28c480bf5aa525538fe/resources/workloads.yaml or do i also need to change the go code?

**Comment by wlan0** [comment]
Hi @sstubbs - This is exactly the use case we are aiming for. If you look at the branch #new-master on this repository, you'll
notice that we are introducing the concept of a StorageTopology. I.e. You can dynamically choose certain drives to be tier1 (SSD), and certain drivers to be tier 2 (HDD), and differentiate between them by their storage classes. 

We are working on this full-time starting this week. Stay tuned for our next release, which will be coming very soon! 

In the meantime, your question is along the correct lines:

> Would I be able to do this by deploying in different namespace or changing https://github.com/minio/direct-csi/blob/e47cddf96a4b857e02ace28c480bf5aa525538fe/resources/workloads.yaml or do i also need to change the go code?

Yes, You can also deploy In the same namespace. Just change the identity name to the one you desire. Also, make sure that it matches for all the different resources (CSIDriver, StorageClass etc.)

You do not need to change the go code.

**Comment by sstubbs** [comment]
This is really great news. Minio really has sorted out every one of my storage problems. Truly great work. I will only be installing the HDDs in a couple weeks so will have a look back then otherwise will change it like you suggest. Thanks a lot for the help.

**Comment by sstubbs** [comment]
I know this is being working on. I was thinking of doing a pr letting people change the values just so you can see what I'm doing and I don't break everything in my cluster when this is released. Looks like kustomize won't allow defaults using env variables according to this issue. https://github.com/kubernetes-sigs/kustomize/issues/2881

Would it make more sense to use helm? I know kustomize allows better customisation but personally I don't need a lot and don't really see how much other people would need it. I could be completely wrong though.

**Comment by sstubbs** [comment]
@wlan0  Sorry please disregard my previous comment. I've been looking at the #new-master branch and this is awesome. I will rather just wait for this to be done than try changing things.

**Comment by sstubbs** [comment]
hi @wlan can I start testing the new-master branch yet?

**Comment by wlan0** [comment]
@sstubbs We have made the v1.0.0 release of direct-csi. Please try it out and let us know!
