### ISSUE TITLE
Pod fails at startup with with error invalid format of /proc/1/mountinfo

### ISSUE THREAD

**Issue by ngbrown** [minio/direct-csi#157]
After installing into MicroK8s (on Ubuntu), the pods tried to start, but they fail to either connect with `Still connecting to unix:///csi/csi.sock` or in the case of `direct-csi`, they are failing to parse the `/proc/1/mountinfo` file correctly.

```
I0127 23:21:48.689837 1544665 init.go:55] obtained client config successfully
Error: invalid format of /proc/1/mountinfo
```

Attached is the contents of `/proc/1/mountinfo`: [mountinfo.txt](https://github.com/minio/direct-csi/files/5883772/mountinfo.txt)

Somewhere near here is probably the issue:
https://github.com/minio/direct-csi/blob/55ddc8c0db6a7a9eee0bc54e1c4c25330d566a34/pkg/sys/mount_discovery.go#L76-L79

I don't think these lines would pass the above test:

```
644 29 0:25 /snapd/ns /run/snapd/ns rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=196804k,nr_inodes=246002,mode=755
662 644 0:4 mnt:[4026532136] /run/snapd/ns/lxd.mnt rw - nsfs nsfs rw
```

From the [kernel documentation](https://www.kernel.org/doc/Documentation/filesystems/proc.txt), that 7th section is optional:

```
3.5	/proc/<pid>/mountinfo - Information about mounts
--------------------------------------------------------

This file contains lines of the form:

36 35 98:0 /mnt1 /mnt2 rw,noatime master:1 - ext3 /dev/root rw,errors=continue
(1)(2)(3)   (4)   (5)      (6)      (7)   (8) (9)   (10)         (11)

(1) mount ID:  unique identifier of the mount (may be reused after umount)
(2) parent ID:  ID of parent (or of self for the top of the mount tree)
(3) major:minor:  value of st_dev for files on filesystem
(4) root:  root of the mount within the filesystem
(5) mount point:  mount point relative to the process's root
(6) mount options:  per mount options
(7) optional fields:  zero or more fields of the form "tag[:value]"
(8) separator:  marks the end of the optional fields
(9) filesystem type:  name of filesystem of the form "type[.subtype]"
(10) mount source:  filesystem specific information or "none"
(11) super options:  per super block options
```

**Comment by wlan0** [comment]
@ngbrown Thanks for the debugging. We've issued the fix. We'll cut a new release with it shortly
