### ISSUE TITLE
Installation fails while discovery of drives

### ISSUE THREAD

**Issue by fbertuzzi** [minio/direct-csi#168]
It already crashed when using `kubectl direct-csi install --crd`

`I0208 22:27:05.973026 7948 init.go:56] obtained client config successfully
E0208 22:27:06.102446 7948 drive_discovery_linux.go:63] Error while probing block device: open /var/lib/direct-csi/devices/sr0: no medium found
E0208 22:27:06.367662 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.369543 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.373214 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.374929 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.376507 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.379426 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.384694 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.387313 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.388820 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.391064 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.392051 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.392929 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.393781 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.394801 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.395631 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
E0208 22:27:06.396474 7948 drive_discovery_linux.go:63] Error while probing block device: EOF
Error: DirectCSIDrive.direct.csi.min.io "7ab0249a9f2209d90d1868ca9a4427199d76411424d8d0bbb3744b67c7538c59" is invalid: status.conditions.reason: Invalid value: "": status.conditions.reason in body should match '^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?`

**Comment by oleludwig** [comment]
This issue seems to be caused by this commit https://github.com/minio/direct-csi/commit/7ca2f4041199d731872f31014caf6ee3742adfa7#diff-2cebc93264c2e1a43db49e9bc1e017d7a852fcab2bb7a02dff109cd1c3317dc2R63 in pkg/sys/drive_discovery_linux.go in line 63/64.
Adding the removed `return nil` fixed the problem for us.

**Comment by wlan0** [comment]
@fbertuzzi @oleludwig I think you're using an older version of direct-csi. Please upgrade using 

```
kubectl krew upgrade direct-csi
kubectl uninstall direct-csi 
kubectl install direct-csi
```

**Comment by oleludwig** [comment]
@wlan0 thanks for the quick response. We have already used this version, so I think that this issue is not fixed yet.

Here is the output of `kubectl krew list`:
PLUGIN      VERSION
direct-csi  v1.2.1
krew        v0.4.0

**Comment by harshavardhana** [comment]
@oleludwig try with v1.2.2 ?

**Comment by oleludwig** [comment]
@harshavardhana Yes, v1.2.2 fixes this issue👍
Thank you
