### ISSUE TITLE
How to remove drives

### ISSUE THREAD

**Issue by bortek** [minio/direct-csi#228]
Hi

Some of the drives were wrong and failed while formatting. 

How do I remove them from the list ?

Using driver version 1.2.8

kubectl direct-csi  drives list
 /dev/sdb2  500 MiB   500 MiB    -        minio-compute-1.dev01.sebshift.sebank.se  Available*  failed to format drive:  mkfs.xfs: cannot open /dev/sdb2: No such device or address
 /dev/sdb3  372 GiB   372 GiB    -        minio-compute-1.dev01.sebshift.sebank.se  Available*  failed to format drive:  mkfs.xfs: cannot open /dev/sdb3: No such device or address

**Comment by bortek** [comment]
Anyone out there who know anything about this and can comment ?

**Comment by wlan0** [comment]
```
Usage:
  direct-csi drives release [flags]

Examples:

 # Release all drives in the cluster
 $ kubectl direct-csi drives release --all
 
 # Release all nvme drives in all nodes 
 $ kubectl direct-csi drives release --drives=/dev/nvme*
 
 # Release all drives from a particular node
 $ kubectl direct-csi drives release --nodes=directcsi-1
 
 # Release all drives based on the access-tier set [hot|cold|warm]
 $ kubectl direct-csi drives release --access-tier=hot
 
 # Combine multiple parameters using multi-arg
 $ kubectl direct-csi drives release --nodes=directcsi-1 --nodes=othernode-2 --status=available
 
 # Combine multiple parameters using csv
 $ kubectl direct-csi drives release --nodes=directcsi-1,othernode-2 --status=ready
 

Flags:
      --access-tier strings   release based on access-tier set. The possible values are [hot,cold,warm] 
  -a, --all                   release all available drives
  -d, --drives strings        glog selector for drive paths
  -h, --help                  help for release
  -n, --nodes strings         glob selector for node names

Global Flags:
      --dry-run             prints the installation yaml
  -k, --kubeconfig string   path to kubeconfig
  -v, --v Level             log level for V logs
  ```

**Comment by bortek** [comment]
This was helpful. Thanks for your reply!!!

**Comment by oshep** [comment]
@wlan0 is there a way to get more details about failing format operations.
When im trying to format empty disk /dev/sdc
`kubectl direct-csi drives format --drives /dev/sdc --nodes=vm02.node`
The drive sdc status is:
`kubectl direct-csi drives list
/dev/sdc   300 GiB   -          -        vm02.node  -            Available*    failed to mount drive:  invalid argument `

Is there a way to get some more details what was going wrong. Which argument is invalid.
Thanks in advance.
