### ISSUE TITLE
How to deal with existing LVM/Software Raided devices

### ISSUE THREAD

**Issue by wlan0** [minio/direct-csi#231]
Needs to be addressed

- Documentation saying we do not support it
- Eventually need to detect it, and possibly allow admin to take actions via direct-csi cli

**Comment by Praveenrajmani** [comment]
drive discovery support for such LVM and software raided drives are added in 
- https://github.com/minio/direct-csi/pull/256
- https://github.com/minio/direct-csi/pull/333
