### ISSUE TITLE
log level for V logs

### ISSUE THREAD

**Issue by oshep** [minio/direct-csi#247]
Hello team.
I'm faced with issue, when i'm using flag '-v' to set "log level for V logs" there are any response that something has been changed.
It would be great to get/see info about:
- What is a current log level?
- What kind of levels are availible? (we know only that "0" used by default)
- How are different log levels affect on commands.
etc.

**Comment by wlan0** [comment]
Hi @oshep,

> I'm faced with issue, when i'm using flag '-v' to set "log level for V logs" there are any response that something has been changed

You'll see more log lines being generated, when you set the v value higher

> What is a current log level?

If you're using the kubectl plugin to install direct-csi, then it is set to 3

> What kind of levels are availible? (we know only that "0" used by default)

0-20

> How are different log levels affect on commands.

The higher the log level, the more logs it will print. If you set it to 5, it'll print all log messages of levels 5 and below

If you set it to 3, it'll print all logs of levels 3 and below


This is the general convention we follow:

```
Verbosity conventions -
1 - things relevant to major functions in the program. eg "bucket created successfully"
2 - things relevant to minor functions in the program. eg "server listening on port: xyz"
3 - function parameters. eg "create bucket bucketname=xyz provisioner=bac"
4 - metrics about inner working of the code itself eg. "function CreateBucket took 145ms to complete on avg"
5 and above - logging actual IO - eg. HTTP req and resp, syscalls etc. 
```

**Comment by wlan0** [comment]
We're also currently improving our logging mechanism. You can track the feature here: https://github.com/minio/direct-csi/issues/253

**Comment by oshep** [comment]
Thanks for answers, @wlan0 !

One more question
>  > What is a current log level?
> If  you're using the kubectl plugin to install direct-csi, then it is set to 3
What I meant was how can we see which log level is currently configured (after changing it, not just after installation).
Or, the log level only applies to the command in which it was specified (is it stateless?)

**Comment by Praveenrajmani** [comment]
> What I meant was how can we see which log level is currently configured
you can see the loglevel by describing the daemonset/deployment running in direct-csi-min-io namespace

```
kubectl describe daemonset/direct-csi-min-io -n direct-csi-min-io
```

There should be `-v=3`, which indicates the default verbosity level (3), you could edit that and re-apply if needed.
