### ISSUE TITLE
Add LUKS support in drive discovery and formatting

### ISSUE THREAD

**Issue by balamurugana** [minio/direct-csi#264]

**Comment by harshavardhana** [comment]
@balamurugana we are recommending not to use LUKS since it doesn't support proper O_DIRECT semantics. (Not sure in latest releases)

In-fact we can error out if LUKS based drives are presented.

**Comment by wlan0** [comment]
@harshavardhana intralinks, one of our potential customers have a security requirement for LUKS. What do you suggest we tell them?

**Comment by wlan0** [comment]
Its just for discovery now. Formatting is not even in the roadmap yet, but might be if we all agree that is the right approach

**Comment by sstubbs** [comment]
currently I'm using LUKS in a separate install not using direct-csi so I can use minio compression. My understanding is that minio compression and encryption cannot be used together. If LUKS cannot be used does this mean encryption and compression cannot be used together if I want to try out direct-csi?

**Comment by sstubbs** [comment]
OK thanks a lot.

**Comment by Praveenrajmani** [comment]
LUKS discovery has been added in the recent releases. Closing this issue.
