### ISSUE TITLE
Add ARM64 builds to krew for M1 MacBooks

### ISSUE THREAD

**Issue by artem-zinnatullin** [minio/direct-csi#285]
Hi, I'm trying to install direct-csi with krew on my M1 MacBook and getting this:

```console
kubectl krew install direct-csi
Updated the local copy of plugin index.
Installing plugin: direct-csi
W0622 19:42:17.098342   62848 install.go:164] failed to install plugin "direct-csi": plugin "direct-csi" does not offer installation for this platform
F0622 19:42:17.098389   62848 root.go:79] failed to install some plugins: [direct-csi]: plugin "direct-csi" does not offer installation for this platform
```

I assume this is due to direct-csi not being built for ARM64. 

Could you please consider adding the support for M1? Example PR from another krew plugin: https://github.com/itaysk/kubectl-neat/pull/60

**Comment by wlan0** [comment]
Thanks for your request. We can definitely add support for ARM64. We’ll add it for the next upcoming release

**Comment by artem-zinnatullin** [comment]
That was quick, thanks, waiting for release then!
