### ISSUE TITLE
Installation of new-master branch

### ISSUE THREAD

**Issue by sstubbs** [minio/direct-csi#29]
Hi,

I've tried quite a few different ways to get the master branch to work with multiple storage classes. I'm having no luck though. How would I install the new-master branch? It doesn't look like it has kustomize files in it.

**Comment by sstubbs** [comment]
should i apply the deployment.yaml and the st.yaml files edited to what I need?

**Comment by harshavardhana** [comment]
It's not ready yet @sstubbs will close this issue for now.
