### ISSUE TITLE
support ability to refresh state of drives

### ISSUE THREAD

**Issue by yee379** [minio/direct-csi#298]
i installed the crd and released that some of the drives on the various servers were incorrectly configured (old disks with too many partitions etc). however, after wiping the disks manually on the server, direct-csi shows both the new wiped disk (ie /dev/sdm) as well as the old partitions (ie /dev/sdm{1,2,3}).

similar other disks on other nodes also simply do not show any changes.

i've tried deleting the pods of the daemonset, natively thinking that it would force a rescan of that particular node, but alas it does not appear to update the content of `kubectl direct-csi drives ls` with the 'correct' information.

it would be handy to offer a `kubectl direct-csi drives rescan` feature.

**Comment by wlan0** [comment]
@yee379 This is a feature we are bringing into v1.4.0, our next release. We plan to make the release as soon as possible, we are currently testing it.

In the meantime, use 

`kubectl direct-csi uninstall --crd --force`

to cleanup the whole setup and rediscover drives from scratch. I'll ping here once the release is out. Stay tuned!

**Comment by yee379** [comment]
thanks, i've been trying v1.4.0rc1 and i appear to get the same error when trying to `format` a drive (`lsblk` output) that already had a partition:

    sdb                       8:16   0   1.8T  0 disk
    └─sdb1                    8:17   0   1.8T  0 part

the output:

    ❯ kubectl direct-csi drives format --nodes srv001 --drives /dev/sdb
    E0713 23:04:11.317829   36733 drives_format.go:169]srv001:/dev/sdb1 already has a fs. Use --force to overwrite
    ❯ kubectl direct-csi drives format --nodes srv001 --drives /dev/sdb --force

    ❯ kubectl direct-csi drives ls --nodes srv001
    ....
     /dev/sdb1  1.8 TiB   -          xfs         -       srv001  -            Available*  failed to mount drive:  invalid argument
    ....

the logs from the `direct-csi` pod on the host

    I0714 06:04:18.384099 23774 drive_controller.go:79] drive update called on 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:04:18.384125 23774 drive_controller.go:209] owning and formatting drive 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:04:19.991087 23774 drive_mounter_linux.go:52] unmounting drive /var/lib/direct-csi/devices/07a225ff-ff03-44de-a4e3-8184d5ff7ef6
    I0714 06:04:37.644740 23774 drive_mounter_linux.go:36] mounting drive /var/lib/direct-csi/devices/07a225ff-ff03-44de-a4e3-8184d5ff7ef6 at /var/lib/direct-csi/mnt/07a225ff-ff03-44de-a4e3-8184d5ff7ef6
    E0714 06:04:37.848010 23774 drive_controller.go:291] failed to mount drive: 9f9fb387-b494-49e0-bc82-98aceb62c091 invalid argument
    I0714 06:04:37.879128 23774 drive_controller.go:79] drive update called on 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:04:37.879153 23774 drive_controller.go:209] owning and formatting drive 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:04:58.902594 23774 drive_mounter_linux.go:36] mounting drive /var/lib/direct-csi/devices/07a225ff-ff03-44de-a4e3-8184d5ff7ef6 at /var/lib/direct-csi/mnt/07a225ff-ff03-44de-a4e3-8184d5ff7ef6
    E0714 06:04:59.128282 23774 drive_controller.go:291] failed to mount drive: 9f9fb387-b494-49e0-bc82-98aceb62c091 invalid argument
    I0714 06:04:59.150814 23774 drive_controller.go:79] drive update called on 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:04:59.150847 23774 drive_controller.go:209] owning and formatting drive 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:05:13.604731 23774 drive_controller.go:79] drive update called on 9aefcda0-f792-4489-b218-a9c3f785780d
    I0714 06:05:13.605102 23774 drive_controller.go:79] drive update called on f726d6eb-5b0d-4a0f-b6cc-49ed9ce26ad3
    I0714 06:05:13.605176 23774 drive_controller.go:79] drive update called on 9c3eb4f8-e8ac-4e5d-9e4b-cbbfe54b59c9
    I0714 06:05:13.605386 23774 drive_controller.go:79] drive update called on 40a5673e-9e49-49b0-ad69-ce5464076bac
    I0714 06:05:13.605441 23774 drive_controller.go:79] drive update called on d883cd4a-9151-4c9d-8955-fc168fcc1b50
    I0714 06:05:13.605531 23774 drive_controller.go:79] drive update called on 8f4981a5-17fd-4bfa-80ad-a4c2de36d58b
    I0714 06:05:13.605855 23774 drive_controller.go:79] drive update called on 8a709fd7-4e4c-4d10-bb96-80ac8b36eaac
    I0714 06:05:13.605871 23774 drive_controller.go:79] drive update called on df0c665e-fb1c-456a-ab1f-d9facab59c1f
    I0714 06:05:13.605861 23774 drive_controller.go:79] drive update called on bfdac043-ce2d-49ba-a030-dc63cd12a938
    I0714 06:05:13.606701 23774 drive_controller.go:79] drive update called on 79635f14-6a36-4178-a788-3e90dcca1e28
    I0714 06:05:13.606856 23774 drive_controller.go:79] drive update called on c1c52f21-0bf6-4d1e-a37b-f63d79ca3023
    I0714 06:05:13.607943 23774 drive_controller.go:79] drive update called on bc8ebcbe-0163-45f9-beef-34add721f950
    I0714 06:05:13.609085 23774 drive_controller.go:79] drive update called on e82e1fed-a2d7-4176-9b5f-a581d5dfcf76
    I0714 06:05:13.609246 23774 drive_controller.go:79] drive update called on 5f8b6b86-6ae4-4aee-8a7b-98c234e3da3e
    I0714 06:05:13.609622 23774 drive_controller.go:79] drive update called on a83d41ea-b94f-4daa-9131-dcfc895845d3
    I0714 06:05:13.609920 23774 drive_controller.go:79] drive update called on ff73cc5c-4898-492b-b125-77f3f727611e
    I0714 06:05:13.609996 23774 drive_controller.go:79] drive update called on 162d337a-3666-457d-8ac3-b20e9d69de5e
    I0714 06:05:13.610254 23774 drive_controller.go:79] drive update called on 9f5bd113-ca44-4641-975a-cb83310dce61
    I0714 06:05:13.610870 23774 drive_controller.go:79] drive update called on a6018e13-cda1-4876-9df5-e38efd022596
    I0714 06:05:13.611041 23774 drive_controller.go:79] drive update called on 003c825a-7288-415a-84ef-a179eec5582a
    I0714 06:05:20.074859 23774 drive_mounter_linux.go:36] mounting drive /var/lib/direct-csi/devices/07a225ff-ff03-44de-a4e3-8184d5ff7ef6 at /var/lib/direct-csi/mnt/07a225ff-ff03-44de-a4e3-8184d5ff7ef6
    E0714 06:05:20.299961 23774 drive_controller.go:291] failed to mount drive: 9f9fb387-b494-49e0-bc82-98aceb62c091 invalid argument
    I0714 06:05:20.314594 23774 drive_controller.go:79] drive update called on 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:05:20.314618 23774 drive_controller.go:209] owning and formatting drive 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:05:41.316638 23774 drive_mounter_linux.go:36] mounting drive /var/lib/direct-csi/devices/07a225ff-ff03-44de-a4e3-8184d5ff7ef6 at /var/lib/direct-csi/mnt/07a225ff-ff03-44de-a4e3-8184d5ff7ef6
    E0714 06:05:41.525839 23774 drive_controller.go:291] failed to mount drive: 9f9fb387-b494-49e0-bc82-98aceb62c091 invalid argument
    E0714 06:05:41.543029 23774 listener.go:277] op: update key: 9f9fb387-b494-49e0-bc82-98aceb62c091 err: Operation cannot be fulfilled on directcsidrives.direct.csi.min.io "9f9fb387-b494-49e0-bc82-98aceb62c091": the object has been modified; please apply your changes to the latest version and try again
    I0714 06:05:41.543106 23774 drive_controller.go:79] drive update called on 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:05:41.543121 23774 drive_controller.go:209] owning and formatting drive 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:06:02.008901 23774 drive_mounter_linux.go:36] mounting drive /var/lib/direct-csi/devices/07a225ff-ff03-44de-a4e3-8184d5ff7ef6 at /var/lib/direct-csi/mnt/07a225ff-ff03-44de-a4e3-8184d5ff7ef6
    E0714 06:06:02.219261 23774 drive_controller.go:291] failed to mount drive: 9f9fb387-b494-49e0-bc82-98aceb62c091 invalid argument
    I0714 06:06:02.252190 23774 drive_controller.go:79] drive update called on 9f9fb387-b494-49e0-bc82-98aceb62c091
    I0714 06:06:02.252212 23774 drive_controller.go:209] owning and formatting drive 9f9fb387-b494-49e0-bc82-98aceb62c091

in addition, console output from srv001 itself started spewing soon after running the format:

     kernel:XFS (sdb1): Superblock has unknown read-only compatible features (0x4) enabled.

any hints as to what i should be checking?

**Comment by Praveenrajmani** [comment]
@yee379 What is the os that you are using? If it Rhel7 compatible, then you might want to use rhel7 image

**Comment by Praveenrajmani** [comment]
Can you also paste `kubectl direct-csi --version` output?

**Comment by yee379** [comment]
woohoo! yep, i'm on a centos7 node - i was able to get the drive into a Ready state using the `--image direct-csi:v1.4.0-rc1-rhel7` image. thanks!

    ❯ kubectl direct-csi --version
    direct-csi version v1.4.0-rc1

FYI i wasn't able to cleanly uninstall:

    ❯ kubectl direct-csi uninstall --crd --force
    Error: Operation cannot be fulfilled on directcsidrives.direct.csi.min.io "5f8b6b86-6ae4-4aee-8a7b-98c234e3da3e": the object has been modified; please apply your changes to the latest version and try again

i ended up force deleting the daemonsets and deployments through kubectl.

should the `kubectl direct-csi install` automatically determine whether my nodes are rhel7 or not? did i miss the documentation around this?

**Comment by Praveenrajmani** [comment]
> Error: Operation cannot be fulfilled on directcsidrives.direct.csi.min.io "5f8b6b86-6ae4-4aee-8a7b-98c234e3da3e": the object has been modified; please apply your changes to the latest version and try again
