### ISSUE TITLE
v1.4.0-rc1: direct-csi daemonset pods in continual crashloopbackoff

### ISSUE THREAD

**Issue by yee379** [minio/direct-csi#299]
i uninstalled (from a successful install and `drive ls`, but unsuccessful `format` of drives) a v1.3.6 with

    ❯ kubectl direct-csi uninstall --crd --force
    I0713 21:32:39.625419  122325 uninstall.go:113] 'direct.csi.min.io' CRD resources deleted
    I0713 21:32:39.682015  122325 uninstall.go:121] 'direct.csi.min.io' crds deleted
    I0713 21:32:39.704811  122325 uninstall.go:128] 'direct.csi.min.io' namespace deleted
    I0713 21:32:39.902480  122325 uninstall.go:136] 'direct.csi.min.io' csidriver deleted
    I0713 21:32:39.928875  122325 uninstall.go:143] 'direct.csi.min.io' storageclass deleted
    I0713 21:32:39.967925  122325 uninstall.go:150] 'direct.csi.min.io' service deleted
    I0713 21:32:40.209952  122325 uninstall.go:157] 'direct.csi.min.io' rbac roles deleted
    I0713 21:32:40.235793  122325 uninstall.go:164] 'direct.csi.min.io' daemonset deleted
    I0713 21:32:40.282168  122325 uninstall.go:177] 'direct.csi.min.io' drive validation rules removed
    I0713 21:32:40.406046  122325 uninstall.go:184] 'direct.csi.min.io' controller deployment deleted
    I0713 21:32:40.554972  122325 uninstall.go:205] 'direct.csi.min.io' conversion deployment deleted

and proceeded with installing v1.4.0rc1 with

    ❯ kubectl direct-csi install --image direct-csi:v1.4.0-rc1
    I0713 21:44:59.134472  129538 install.go:98] 'direct.csi.min.io' namespace created
    I0713 21:45:03.303969  129538 install.go:105] 'direct.csi.min.io' conversion deployment created
    I0713 21:45:03.496944  129538 install.go:126] crds successfully registered
    I0713 21:45:03.666683  129538 install.go:135] 'direct.csi.min.io' csidriver created
    I0713 21:45:03.722343  129538 install.go:144] 'direct.csi.min.io' storageclass created
    I0713 21:45:03.750259  129538 install.go:153] 'direct.csi.min.io' service created
    I0713 21:45:03.817592  129538 install.go:162] 'direct.csi.min.io' rbac roles created
    I0713 21:45:03.848337  129538 install.go:171] 'direct.csi.min.io' daemonset created
    I0713 21:45:08.213608  129538 install.go:180] 'direct.csi.min.io' deployment created

all pods except for the daemonset pods come up okay: the logs for the `direct-csi` pods are:

    I0714 04:51:25.904202     524 run.go:76] The conversion webhook is live!
    I0714 04:51:25.905376     524 init.go:60] obtained client config successfully
    Error: the server could not find the requested resource (get directcsidrives.direct.csi.min.io)
this

    ❯ kubectl get crd directcsidrives.direct.csi.min.io
    NAME                                CREATED AT
    directcsidrives.direct.csi.min.io   2021-07-14T04:45:03Z

**Comment by Praveenrajmani** [comment]
@yee379 looks like the direct-csi client you are using is not v1.4.0, please install and use the latest client (kubectl-direct_csi_1.4.0-rc1_*) from https://github.com/minio/direct-csi/releases/tag/v1.4.0-rc1

**Comment by yee379** [comment]
great! thanks! in terms of installing the latest client, i ended up downloading the binary and copying it into 

    ~/.krew/store/direct-csi/v1.4.0rc1/kubectl-direct_csi

and then modified my symlinks 

    ~/.krew/bin/kubectl-direct_csi -> ../store/direct-csi/v1.4.0rc1/kubectl-direct_csi

pods are up! cheers,
