### ISSUE TITLE
some useability suggestions

### ISSUE THREAD

**Issue by yee379** [minio/direct-csi#302]
- it would be great to have the 'status' of the drive update to something like 'preparing' as soon as a drive is being prep'd from being Available into the Ready state.
- globs are great, however, it would be handy to support bash expansions like `/dev/sd{b..z}`
- the allocated column appears to report an incorrect value:

    /dev/sdb1  1.8 TiB   964 MiB    xfs         -        ltda-srv001  -            Ready

`lsblk` shows:

    sdb                       8:16   0   1.8T  0 disk
    └─sdb1                    8:17   0   1.8T  0 part /var/lib/direct-csi/mnt/07a225ff-ff03-44de-a4e3-8184d5ff7ef6

**Comment by Praveenrajmani** [comment]
> /dev/sdb1 1.8 TiB 964 MiB xfs - ltda-srv001 - Ready

**Comment by yee379** [comment]
duh! my apologies; i misread the units on the allocated.

**Comment by wlan0** [comment]
> it would be great to have the 'status' of the drive update to something like 'preparing' as soon as a drive is being prep'd from being Available into the Ready state.

I see. This would allow users to know that formatting is in progress. I need to think about the name and the state transitions some more. 

> globs are great, however, it would be handy to support bash expansions like /dev/sd{b..z}

This is duly noted. I think this is a great suggestion. We can add this to the pipeline.

**Comment by yee379** [comment]
hmmm... so i have a server with 12 drives that i wish to present to direct-csi. they are 2TB drives like all the other drives in the servers that i have (which all seem okay):

    ❯ lsblk
    NAME                    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
    ...
    sdb                       8:16   0   1.8T  0 disk
    └─sdb1                    8:17   0   1.8T  0 part /var/lib/direct-csi/mnt/4b715b43-e676-45b3-a588-b62ef54b6784
    sdc                       8:32   0   1.8T  0 disk
    └─sdc1                    8:33   0   1.8T  0 part /var/lib/direct-csi/mnt/bdef9c8b-96eb-4a5e-86ed-477e13fd80c0
    sdd                       8:48   0   1.8T  0 disk
    └─sdd1                    8:49   0   1.8T  0 part /var/lib/direct-csi/mnt/9511d8bc-8928-477f-a363-c728e9efb7eb
    sde                       8:64   0   1.8T  0 disk
    └─sde1                    8:65   0   1.8T  0 part /var/lib/direct-csi/mnt/b14330bc-92b7-406b-b8d9-674c4c021d5a
    sdf                       8:80   0   1.8T  0 disk
    └─sdf1                    8:81   0   1.8T  0 part /var/lib/direct-csi/mnt/e9d4cc3b-9bfe-4df3-83cf-12de91b3193a
    sdg                       8:96   0   1.8T  0 disk
    └─sdg1                    8:97   0   1.8T  0 part /var/lib/direct-csi/mnt/77d93014-0c52-4ec3-badb-e5ceacbf1dfc
    sdh                       8:112  0   1.8T  0 disk
    └─sdh1                    8:113  0   1.8T  0 part /var/lib/direct-csi/mnt/bda0ead8-2882-4ad4-8b3a-6d279529e53a
    sdi                       8:128  0   1.8T  0 disk
    └─sdi1                    8:129  0   1.8T  0 part /var/lib/direct-csi/mnt/9265eea9-3ff1-4a4b-97f0-fd0fe95b04d0
    sdj                       8:144  0   1.8T  0 disk
    └─sdj1                    8:145  0   1.8T  0 part /var/lib/direct-csi/mnt/95a57c19-ff16-408f-87df-1659f0107e56
    sdk                       8:160  0   1.8T  0 disk
    └─sdk1                    8:161  0   1.8T  0 part /var/lib/direct-csi/mnt/efb506ef-e69b-4689-9c5c-fefda8c944de
    sdl                       8:176  0   1.8T  0 disk
    └─sdl1                    8:177  0   1.8T  0 part /var/lib/direct-csi/mnt/b589e77c-f69d-427e-b4fb-183ff4ddd199
    sdm                       8:192  0   1.8T  0 disk
    └─sdm1                    8:193  0   1.8T  0 part /var/lib/direct-csi/mnt/d1268b72-bd3d-4cd0-896e-245084ee67f7

however, 

    ❯ kubectl direct-csi drives ls
     /dev/sdb1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdc1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdd1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sde1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdf1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdg1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdh1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdi1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdj1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdk1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdl1  1024 MiB  16 EiB     xfs         -        srv003  -            Ready
     /dev/sdm1  1.8 TiB   964 MiB    xfs         -        srv003  -            Ready

i'm pretty sure i'm reading the units right this time: its claiming the drives are only 1GiB and that its been allocated 16Exabyte? the last drive at /dev/sdm1 seems correct tho.

i have been uninstalling and reinstalling direct-csi a lot. i've also cleared the drives using 

    kubectl get directcsidrives.direct.csi.min.io --no-headers | awk '{print $1}' | xargs kubectl delete directcsidrives.direct.csi.min.io

prior to this install.

**Comment by wlan0** [comment]
Can you please paste the output of

` kubectl get directcsidrives -o yaml $drive_id` 

Where drive_id is the id of one of the faulty drives (showing 16 exabytes). You can obtain it from the output of 

`kubectl direct-csi drives ls -o wide`

I’m assuming you’re on 1.4.0-rc1. This wide command won’t work unless you’re using the newer version of the client

**Comment by yee379** [comment]
❯ kubectl get directcsidrives -o yaml 9840cba0-d390-4731-ab41-c5f5c6d69452
    apiVersion: direct.csi.min.io/v1beta2
    kind: DirectCSIDrive
    metadata:
      creationTimestamp: "2021-07-14T23:39:20Z"
      finalizers:
      - direct.csi.min.io/data-protection
      generation: 3
      labels:
        direct.csi.min.io/access-tier: Unknown
        direct.csi.min.io/created-by: directcsi-driver
        direct.csi.min.io/node: srv003
        direct.csi.min.io/path: sdb-part-1
        direct.csi.min.io/version: v1beta2
      name: 9840cba0-d390-4731-ab41-c5f5c6d69452
      resourceVersion: "3114779"
      uid: ab33d4cf-d4a2-4fdd-bfda-d57330bc0668
    spec:
      directCSIOwned: true
    status:
      accessTier: Unknown
      allocatedCapacity: -1997758050304
      conditions:
      - lastTransitionTime: "2021-07-14T23:43:25Z"
        message: ""
        reason: Added
        status: "True"
        type: Owned
      - lastTransitionTime: "2021-07-14T23:43:25Z"
        message: Mounted
        reason: Added
        status: "True"
        type: Mounted
      - lastTransitionTime: "2021-07-14T23:43:25Z"
        message: Formatted
        reason: Added
        status: "True"
        type: Formatted
      - lastTransitionTime: "2021-07-14T23:39:20Z"
        message: ""
        reason: Initialized
        status: "True"
        type: Initialized
      driveStatus: Ready
      filesystem: xfs
      filesystemUUID: 4b715b43-e676-45b3-a588-b62ef54b6784
      freeCapacity: 1998831779840
      logicalBlockSize: 512
      majorNumber: 8
      minorNumber: 17
      mountpoint: /var/lib/direct-csi/mnt/4b715b43-e676-45b3-a588-b62ef54b6784
      nodeName: srv003
      partitionNum: 17
      partitionUUID: BAB55744-489A-45E1-AD35-9526A2D147B6
      path: /var/lib/direct-csi/devices/sdb-part-1
      physicalBlockSize: 4096
      rootPartition: sdb
      serialNumber: 00fc7e0528afc581
      topology:
        direct.csi.min.io/identity: direct-csi-min-io
        direct.csi.min.io/node: srv003
        direct.csi.min.io/rack: default
        direct.csi.min.io/region: default
        direct.csi.min.io/zone: default
      totalCapacity: 1073729536

**Comment by Praveenrajmani** [comment]
Can you just do, 

```
kubectl direct-csi uninstall 
```

**Comment by yee379** [comment]
that fixed it 
```
    ❯ kubectl direct-csi uninstall
    ❯ kubectl direct-csi install --image direct-csi:v1.4.0-rc1-rhel7
    ❯ kubectl direct-csi drives ls -o wide
    ...
     /dev/sdb1  1.8 TiB   963 MiB    xfs         -        ltda-srv003  -            Ready        9840cba0-d390-4731-ab41-c5f5c6d69452
    ...
```

**Comment by Praveenrajmani** [comment]
We need to understand how we got into that state anyway, can you please help us to reproduce that?

**Comment by yee379** [comment]
no, i don't. everything looks okay.

i had rebuilt the jbod (unfortunately these are raid-0 single disks as the raid controller doesn't support passthru) a few times. but after each time, i had always done a full `uninstall --crd --force`. i rarely reboot the server as the disks appear to be detected by the OS fine.

what is the recommended way for get direct-csi to refresh/rescan disks on a server?

**Comment by Praveenrajmani** [comment]
> what is the recommended way for get direct-csi to refresh/rescan disks on a server?
