### ISSUE TITLE
Pod and PVC stuck in Pending: "Cannot satisfy the topology constraint"

### ISSUE THREAD

**Issue by buccella** [minio/direct-csi#317]
I'm unsure that this is a bug in direct-csi, but is at least something that should probably be mentioned in documentation.

**Environment**

Three worker nodes:
```
$ kubectl get nodes | grep -v control-plane
NAME             STATUS   ROLES                  AGE   VERSION
chris1-min1      Ready    <none>                 13d   v1.20.2
chris1-min2      Ready    <none>                 13d   v1.20.2
chris1-min3      Ready    <none>                 13d   v1.20.2
```
Only the first two have formatted disks for direct-csi:
```
$ kubectl direct-csi drive ls --status 'Ready','InUse'
 DRIVE     CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE         ACCESS-TIER  STATUS
 /dev/sdb  30 GiB    24 GiB     xfs         2        chris1-min1  -            InUse
 /dev/sdb  30 GiB    24 GiB     xfs         2        chris1-min2  -            InUse
```
Two pods created, each with 2 12Gi PVCs:
```
$ kubectl direct-csi volumes ls
 VOLUME                                    CAPACITY  NODE         DRIVE  PODNAME               PODNAMESPACE
 pvc-fa472dc8-abca-4794-b143-7ae3834c4a4f  12 GiB    chris1-min1  sdb    vl-test-dcsi-2x12g-2  default
 pvc-ceed343a-8bd8-4a31-bd94-7e104391ba79  12 GiB    chris1-min1  sdb    vl-test-dcsi-2x12g-2  default
 pvc-d6e8e62e-f0e3-4a02-93e3-6cde329586d7  12 GiB    chris1-min2  sdb    vl-test-dcsi-2x12g-1  default
 pvc-eefdacaf-13a6-47f3-8387-cb83096ba260  12 GiB    chris1-min2  sdb    vl-test-dcsi-2x12g-1  default
```

**Problem**

Now there is capacity still available on min1 and min2. But when creating another pod with a 4Gi PVC, the pod and PVC will be stuck in pending, with the following errors:

For the pod:
```
Warning  FailedScheduling  46s   default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "vl-test-local-claim-4g-1"
```

And the PVC:
```
  Normal   WaitForFirstConsumer  71s                persistentvolume-controller                                                               waiting for first consumer to be created before binding
  Normal   ExternalProvisioning  2s (x10 over 71s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "direct-csi-min-io" or manually created by system administrator
  Normal   Provisioning          2s (x9 over 71s)   direct-csi-min-io_direct-csi-min-io-6998bdf4d-qhj9k_76d7f5d3-6cc8-4787-ad93-add70405aa09  External provisioner is provisioning volume for claim "default/vl-test-local-claim-4g-1"
  Warning  ProvisioningFailed    2s (x9 over 71s)   direct-csi-min-io_direct-csi-min-io-6998bdf4d-qhj9k_76d7f5d3-6cc8-4787-ad93-add70405aa09  failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = Cannot satisfy the topology constraint
  Normal   WaitForPodScheduled   2s (x13 over 71s)  persistentvolume-controller                                                               waiting for pod vl-test-dcsi-4g-1 to be scheduled
```

The log on min3 provides a little more detail:
```
$ kubectl -n direct-csi-min-io logs direct-csi-min-io-6998bdf4d-qhj9k -c direct-csi
...
"Cannot satisfy the topology constraint" volume="pvc-9c3a2514-e0e7-4ee3-99bc-8cdcd3c8442c" 
preferredTopology=[segments:<key:"direct.csi.min.io/identity" value:"direct-csi-min-io" > segments:<key:"direct.csi.min.io/node" value:"chris1-min3" > segments:<key:"direct.csi.min.io/rack" value:"default" > segments:<key:"direct.csi.min.io/region" value:"default" > segments:<key:"direct.csi.min.io/zone" value:"default" > ] 
requisiteTopology=[segments:<key:"direct.csi.min.io/identity" value:"direct-csi-min-io" > segments:<key:"direct.csi.min.io/node" value:"chris1-min3" > segments:<key:"direct.csi.min.io/rack" value:"default" > segments:<key:"direct.csi.min.io/region" value:"default" > segments:<key:"direct.csi.min.io/zone" value:"default" > ]
```

So the pod is being scheduled to a node that doesn't have any direct-csi formatted drives available. 

I've found the following work as solutions:
1. using a `nodeSelector` in the pod spec
2. setting `volumeBindingMode: Immediate` in the StorageClass
3. removing the `direct.csi.min.io` labels from min3

What is the best solution here?

**Comment by wlan0** [comment]
Could you please share the volumeClaim templates from your pod and the storageClass definition by the name 'direct-csi-min-io'.

I do not believe it is a bug, because we use VolumeBindingMode: "WaitForFirstConsumer", which figures out scheduling first, then allocates from the available volumes. Unless your podSpec has an antiaffinity or the nodes have a taint on them, direct-csi will get all 3 nodes as possible options. 

Finally, on node 3, you're looking at the controller logs, not the driver logs. There will be another direct-csi pod on node3, whose name will be shorter. If those logs show some reaction to this volume request, then it is trying to schedule on node3.

**Comment by buccella** [comment]
@wlan0 thanks for your quick reply.

```
$ kubectl get sc direct-csi-min-io -o yaml
allowVolumeExpansion: false
allowedTopologies:
- matchLabelExpressions:
  - key: direct.csi.min.io/identity
    values:
    - direct-csi-min-io
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    created-by: kubectl/direct-csi
  creationTimestamp: "2021-08-04T20:24:52Z"
  labels:
    app: direct.csi.min.io
    type: CSIDriver
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:allowVolumeExpansion: {}
      f:allowedTopologies: {}
      f:metadata:
        f:annotations:
          .: {}
          f:created-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:type: {}
      f:parameters:
        .: {}
        f:fstype: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: kubectl-direct_csi
    operation: Update
    time: "2021-08-04T20:24:52Z"
  name: direct-csi-min-io
  resourceVersion: "3974933"
  uid: 118f6f25-58ae-4330-ba32-a84fdc9c7b72
parameters:
  fstype: xfs
provisioner: direct-csi-min-io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

Here is the yaml for the Pod and 4Gi PVC. The other two Pods are the same, except each has 2 12Gi PVCs instead of 1.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vl-test-local-claim-4g-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: direct-csi-min-io
---
kind: Pod
apiVersion: v1
metadata:
  name: vl-test-dcsi-4g-1
spec:
  containers:
  - name: vl-test-ls
    image: gcr.io/google_containers/busybox
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "while [ 1 ]; do echo \"$(date)\" >> /mnt/one/SUCCESS; sleep 30; done"
    volumeMounts:
      - name: ls-pvc1
        mountPath: "/mnt/one"
  volumes:
    - name: ls-pvc1
      persistentVolumeClaim:
        claimName: vl-test-local-claim-4g-1
```

No taints on any of the worker nodes.

**Comment by wlan0** [comment]
> No taints on any of the worker nodes.

Understood. I just took another look at the logs you pasted in your first comment

```
Cannot satisfy the topology constraint" volume="pvc-9c3a2514-e0e7-4ee3-99bc-8cdcd3c8442c" 
preferredTopology=[segments:<key:"direct.csi.min.io/identity" value:"direct-csi-min-io" > segments:<key:"direct.csi.min.io/node" value:"chris1-min3" > segments:<key:"direct.csi.min.io/rack" value:"default" > segments:<key:"direct.csi.min.io/region" value:"default" > segments:<key:"direct.csi.min.io/zone" value:"default" > ] 
requisiteTopology=[segments:<key:"direct.csi.min.io/identity" value:"direct-csi-min-io" > segments:<key:"direct.csi.min.io/node" value:"chris1-min3" > segments:<key:"direct.csi.min.io/rack" value:"default" > segments:<key:"direct.csi.min.io/region" value:"default" > segments:<key:"direct.csi.min.io/zone" value:"default" > ]
```

The requisite and preferred topology are inputs from kubernetes. Kubernetes, at the point of scheduling that pod decided that the pod SHOULD NOT run on any node other than chris-min3. It might've been because of memory or cpu constraints. Were nodes `chris-min1`, `chris-min2` overloaded at that point in time by any chance? 

In terms of steps to move forward, the right solution is using the `nodeSelector` as you suggested. `Immediate` Binding mode is the wrong mode for direct-csi. Removing `direct.csi.min.io` labels will make the node unschedulable for pods that need direct-csi volumes. In larger, and more dynamic environments, this practice is not recommended.

The other option is to restrict nodes during install time. In the install command, there is a nodeSelector flag, that accepts arbitrary kv pairs. Any node that has labels specified during install will run direct-csi and other wont.

**Comment by buccella** [comment]
> Were nodes `chris-min1`, `chris-min2` overloaded at that point in time by any chance?

No, the only workload is one tiny test pod on each. 

`min3` does have direct-csi pods running on it, and is labeled with `direct.csi.min.io/*` labels. Is it possible that the Kubernetes scheduler is selecting `min3` on that basis, but direct-csi can't create a PV on `min3` because that node has no `Ready` drives?

**Comment by wlan0** [comment]
> Is it possible that the Kubernetes scheduler is selecting min3 on that basis, but direct-csi can't create a PV on min3 because that node has no Ready drives?

Yes, that is what is going on.

**Comment by Praveenrajmani** [comment]
closing this issue for now, please feel free to re-open if you have anymore questions.
