### ISSUE TITLE
Management of directories of deleted PVs

### ISSUE THREAD

**Issue by buccella** [minio/direct-csi#323]
With the `ReclaimPolicy` set to `Delete`, the deletion of a PVC will result in the PV deleted. But the PV's directory in `/var/lib/direct-csi/mnt/<dcsi_drive_id>/` remains. It would be nice to have a convenient way to manage these remnants. For example, the [nfs-client-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) is tunable to allow for the directories of deleted PVs to be deleted from the filesystem, or moved to an archive directory.

**Comment by wlan0** [comment]
hi @buccella! 

We do cleanup the directory from which the volume was provisioned. If it still remains, then the volume api object or the corresponding PVC/PV is likely still around. Can you check and confirm if both the directcsivolume, PV and PVCs are gone. As in, no more finalizers remain. 

For instance, even after you call delete on a PVC, if a pod is stuck in terminating state and holding the PV from going away, direct-csi will not receive the delete call.

**Comment by Praveenrajmani** [comment]
Not cleaning up the PV directories upon deletion looks like a bug. I was able to reproduce this. Will send a fix shortly.

Thanks for reporting @buccella
