### ISSUE TITLE
CSI of block interface

### ISSUE THREAD

**Issue by lllllhhhy** [minio/direct-csi#327]
May I know if Minio Direct CSI already finished the work for block device CSI that we can assign /dev/sda-sdd into minio CSI directly. And could you please show me some guide and example about how to use it if it has been finished?

**Comment by wlan0** [comment]
We do not support block volumes right now. However, you can rely on direct-csi to provision a volume that occupies the entire block device if that helps with your case. Let us know you use case in more detail, maybe we can offer better suggestion if we understand your use case more.

**Comment by lllllhhhy** [comment]
May I contact with you in slack for more details?

**Comment by wlan0** [comment]
Yes please. Find me @wlan0 on minio slack.

**Comment by Praveenrajmani** [comment]
Closing this issue for now, Please feel free to re-open if you have anymore questions
