### ISSUE TITLE
Compatibilty with Nomad

### ISSUE THREAD

**Issue by sycured** [minio/direct-csi#341]
I use Nomad and I can't run direct-csi (directly the binary) because it's looking for a kubeconfig that doesn't exist with Nomad.

Is it possible to have direct-csi compatible with Nomad?

**Comment by harshavardhana** [comment]
What is nomad? is it k8s compatible?

**Comment by sycured** [comment]
This orchestrator: https://www.nomadproject.io/

**Comment by harshavardhana** [comment]
direct-csi is a CSI built around k8s APIs unfortunately it won't support nomad - unless nomad starts supporting k8s APIs

**Comment by sycured** [comment]
@harshavardhana can you build an hybrid CSI working with k8s and nomad?

For example, Portworx did it

**Comment by harshavardhana** [comment]
> @harshavardhana can you build an hybrid CSI working with k8s and nomad?
> 
> For example, Portworx did it

Right now its not a priority for us.

**Comment by sycured** [comment]
Ok thank you… so I'll migrate to another solution.
Thanks and I hope that a day you'll add it to your roadmap

**Comment by nahsi** [comment]
Why take the open standard (CSI) and then glue it to something like K8S?
