### ISSUE TITLE
Install logs

### ISSUE THREAD

**Issue by wlan0** [minio/direct-csi#385]
On every install create 2 local files
- one which has the kube resources that were just created, and 
- another that has the version of client, image names, params passed in, along with execution logs

the filenames of the two files should follow the format (for one installation, the timestamps should match exactly)
```
logFile - direct-csi.install.log.${timestamp}
resourceFile - direct-csi.yaml.${timestamp} 
```

**Comment by Praveenrajmani** [comment]
Fixed in https://github.com/minio/direct-csi/pull/395
