### ISSUE TITLE
About minio combining with K8S 

### ISSUE THREAD

**Issue by fantastic2085** [minio/direct-csi#4]
![image](https://user-images.githubusercontent.com/4116773/86321072-d4be0680-bc6a-11ea-9904-834a27a2cb1f.png)

I drew a simple structure diagram to express my idea more clearly
Your efficiency is too high. I haven't had time to upload this structure drawing

**Would like to consult, the above deployment, whether feasible?**

The question mark in the structure drawing is my question

I want to know **how to use minio clustering when K8S deploys an app that doesn't use S3**?

**Comment by fantastic2085** [comment]
@harshavardhana can not see the picture?

**Comment by wlan0** [comment]
@fantastic2085 Based on the picture, did you mean that each volume request will provision 4 underlying drives? If that's the question, then NO. Each volume request will only provision a sub-dir from one underlying drive only. If you want to use multiple volumes within one pod, you need to make multiple volume claim requests
