### ISSUE TITLE
Cannot generate deploy yaml on baremetal cluster

### ISSUE THREAD

**Issue by lrojas89** [minio/direct-csi#404]
I tried to deploy a custom installation in baremetal cluster of k8s and I get this error when execute the command
`kubectl direct-csi install --dry-run > direct-csi-install.yaml`, the output string at the end of the generated yaml is `ERROR CA bundle is empty`

Can you help me?

**Comment by Praveenrajmani** [comment]
Hi @lrojas89 

Is direct-csi already running in the cluster? If so, can you uninstall the existing setup using `kubectl direct-csi uninstall` and then try to generate the yaml using `kubectl direct-csi install --dry-run`

And also what version of direct-csi are you using? - `kubectl direct-csi --version`
