### ISSUE TITLE
Can I add USB disk to direct-csi?

### ISSUE THREAD

**Issue by romqn1999** [minio/direct-csi#422]
Hello team, I have a disk named `/dev/sdb/` connected to my machine through USB port:
```sh
$ sudo lshw
machine-01             
    description: Desktop Computer
    product: To Be Filled By O.E.M. (To Be Filled By O.E.M.)
    vendor: To Be Filled By O.E.M.
    version: To Be Filled By O.E.M.
    serial: To Be Filled By O.E.M.
    width: 64 bits
    capabilities: smbios-2.8 dmi-2.8 smp vsyscall32
    configuration: boot=normal chassis=desktop family=To Be Filled By O.E.M. sku=To Be Filled By O.E.M. uuid=00020003-0004-0005-0006-000700080009
...
     *-scsi:1
          physical id: 13
          logical name: scsi4
        *-disk
             description: SCSI Disk
             product: nal USB 3.0
             vendor: TO Exter
             physical id: 0.0.0
             bus info: scsi@4:0.0.0
             logical name: /dev/sdb
             logical name: /mnt/sdb
             version: 0104
             serial: 2015033100081
             size: 5589GiB (6001GB)
             configuration: ansiversion=6 logicalsectorsize=512 mount.fstype=xfs mount.options=rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota sectorsize=4096 state=mounted
...
```
```sh
$ lsblk -a
sda      8:0    0   1,8T  0 disk 
├─sda1   8:1    0   1,8T  0 part /
├─sda2   8:2    0     1K  0 part 
└─sda5   8:5    0   976M  0 part 
sdb      8:16   0   5,5T  0 disk /mnt/sdb
```

and when I check drives on that machine with direct-csi, I don't see the USB disk:
```sh
$ kubectl direct-csi drives ls -a -n machine-01
 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE        ACCESS-TIER  STATUS          
 /dev/sda1  1.8 TiB   981 GiB    ext4        -        machine-01  -            Unavailable
```

My question is Can I add USB disk to direct-csi?

**Comment by Praveenrajmani** [comment]
@romqn1999 Can you restart the direct-csi pod running on that node once? And then do `kubectl direct-csi drives ls --all`?

**Comment by romqn1999** [comment]
> Can you restart the direct-csi pod running on that node once?

I am unable to restart the direct-csi pod running on that node with `kubectl rollout restart`:
```sh
$ kubectl rollout restart -n direct-csi-min-io pod/direct-csi-min-io-lh88v
error: pods "direct-csi-min-io-lh88v" restarting is not supported
```
so can you help me the command to restart the direct-csi pod running on that node

**Comment by Praveenrajmani** [comment]
@romqn1999  you can do the following steps to restart direct-csi completely

```
kubectl direct-csi uninstall
kubectl direct-csi install
```

**Comment by Praveenrajmani** [comment]
Or you can delete that pod using `kubectl delete pod <podname> -n direct-csi-min-io`

**Comment by romqn1999** [comment]
> Or you can delete that pod using `kubectl delete pod <podname> -n direct-csi-min-io`

Thank you, I have restart the direct-csi pod running on that node by using `kubectl delete pod`:
```sh
$ kubectl delete pod direct-csi-min-io-lh88v -n direct-csi-min-io
pod "direct-csi-min-io-lh88v" deleted
```
And then I can see the usb disk `/dev/sdb` was listed now:
```sh
$ kubectl direct-csi drives ls -a -n machine-01
 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE        ACCESS-TIER  STATUS          
 /dev/sda1  994 GiB   322 GiB    ext4        -        machine-01  -            Unavailable     
 /dev/sdb   5.5 TiB   45 GiB     ext4        -        machine-01  -            Available
 ```

**Comment by Praveenrajmani** [comment]
@romqn1999 Dynamic discovery feature is been actively worked upon and will be available in the next release. Where you don't need to necessarily restart the direct-csi pods to re-run the discovery.

One more change is to umount `/dev/sdb`. Looks like it is been mounted in `/mnt`  which won't be recognized by direct-csi. DirectCSI works with confined volume mappings and do not have access to certain host directories like `/mnt`.
