### ISSUE TITLE
Error initializing operator on GCP

### ISSUE THREAD

**Issue by ilyusha** [minio/direct-csi#424]
Running `kubectl direct-csi install` results in the following error:

_Error: could not initialize kube client: err=no Auth Provider found for name "gcp"_

direct-cli version 1.4.3
kubectl version 1.19 (but also tested on 1.22)

I strongly suspect this might be fixed by https://github.com/minio/direct-csi/pull/391, but it doesn't seem to be in the latest release.

**Comment by wlan0** [comment]
Hi @ilyusha,

Yes, at that version, we were'nt initializing cloud specific clients. We are releasing a patch version for a different  bug, we'll add support for gcp as well along with that change. I will update here on this issue once the patch is released.

**Comment by ilyusha** [comment]
Thank you @wlan0! Lookin forward to it.

**Comment by wlan0** [comment]
@ilyusha The latest release has support for GCP credential provider
