### ISSUE TITLE
kubectl krew install direct-csi fails with 'checksum does not match'

### ISSUE THREAD

**Issue by bet-me** [minio/direct-csi#452]
The latest version is v1.4.6. I can't find v1.4.4 in the official releases.

```
kubectl krew version
OPTION            VALUE
GitTag            v0.4.2
GitCommit         6fcdb79
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /Volumes/MacintoshSSD/Users/steve/.krew
IndexPath         /Volumes/MacintoshSSD/Users/steve/.krew/index/default
InstallPath       /Volumes/MacintoshSSD/Users/steve/.krew/store
BinPath           /Volumes/MacintoshSSD/Users/steve/.krew/bin
DetectedPlatform  darwin/amd64
steve@Steves-Mac-Pro-2 ~ % 
steve@Steves-Mac-Pro-2 ~ % kubectl krew install direct-csi
Updated the local copy of plugin index.
Installing plugin: direct-csi
W1124 10:06:16.177684   94125 install.go:164] failed to install plugin "direct-csi": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 0568537e084dddd8b3e9fc6d2fde1a7dc2560c383839618051175e4c3f61fb37, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
F1124 10:06:16.177789   94125 root.go:79] failed to install some plugins: [direct-csi]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 0568537e084dddd8b3e9fc6d2fde1a7dc2560c383839618051175e4c3f61fb37, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000192001, 0xc0003a21c0, 0x156, 0x1ab)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
```

**Comment by Feldermann** [comment]
Same here:
OPTION            VALUE
GitTag            v0.4.2
GitCommit         6fcdb79
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /home/blue/.krew
IndexPath         /home/blue/.krew/index/default
InstallPath       /home/blue/.krew/store
BinPath           /home/blue/.krew/bin
DetectedPlatform  linux/amd64

Updated the local copy of plugin index.
Installing plugin: direct-csi
W1124 13:40:00.354334    2245 install.go:164] failed to install plugin "direct-csi": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does             not match, want: 1c940a1431e833801c3192ac6c54ba1321f5d8c21b4eb85b10729c9d37de11b7, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
F1124 13:40:00.354414    2245 root.go:79] failed to install some plugins: [direct-csi]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum do            es not match, want: 1c940a1431e833801c3192ac6c54ba1321f5d8c21b4eb85b10729c9d37de11b7, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0001a61c0, 0x156, 0x1ab)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0xea5d20, 0xc000000003, 0x0, 0x0, 0xc00020e0e0, 0xc12ae0, 0x7, 0x4f, 0x40e000)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0xea5d20, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000054f20, 0x1, 0x1)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1489
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
        /home/runner/work/krew/krew/cmd/krew/cmd/root.go:79 +0x254
main.main()
        /home/runner/work/krew/krew/cmd/krew/main.go:25 +0x45

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0xea5d20)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x7fa45fe7eed8, 0x72, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000391218, 0x72, 0xe00, 0xe04, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.16.8/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000391200, 0xc00036e000, 0xe04, 0xe04, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000391200, 0xc00036e000, 0xe04, 0xe04, 0x121, 0xc0000de7d8, 0x14)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0001cc000, 0xc00036e000, 0xe04, 0xe04, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc000182060, 0xc00036e000, 0xe04, 0xe04, 0x500, 0xc000080000, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc00029acf8, 0xb4dce0, 0xc000182060, 0x40b6a5, 0x9fff80, 0xa6baa0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc00029aa80, 0xb4e920, 0xc0001cc000, 0x5, 0xc0001cc000, 0x418973)
        /opt/hostedtoolcache/go/1.16.8/x64/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00029aa80, 0x0, 0x0, 0xc000350020)
        /opt/hostedtoolcache/go/1.16.8/x64/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc00029aa80, 0xc000200000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc0000c9a40, 0xc0000b22d8, 0x9, 0x9, 0x6f9a4b, 0xc0000dec78, 0x406fa5)
        /opt/hostedtoolcache/go/1.16.8/x64/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0xb4db80, 0xc0000c9a40, 0xc0000b22d8, 0x9, 0x9, 0x9, 0xc000054330, 0x6afd00cca36800, 0xc000054330)
        /opt/hostedtoolcache/go/1.16.8/x64/src/io/io.go:328 +0x87
io.ReadFull(...)
        /opt/hostedtoolcache/go/1.16.8/x64/src/io/io.go:347
net/http.http2readFrameHeader(0xc0000b22d8, 0x9, 0x9, 0xb4db80, 0xc0000c9a40, 0x0, 0x0, 0xc00022e600, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0000b22a0, 0xc00022e600, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc0000defa8, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/h2_bundle.go:8331 +0xd8
net/http.(*http2ClientConn).readLoop(0xc00018e300)
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/h2_bundle.go:8253 +0x6f
created by net/http.(*http2Transport).newClientConn
        /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/h2_bundle.go:7217 +0x6c5

**Comment by Praveenrajmani** [comment]
This PR https://github.com/kubernetes-sigs/krew-index/pull/1782 will update the krew-index with the latest version. Stay tuned and thanks for reporting!
