### ISSUE TITLE
Setup krew release automation

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/direct-csi#453]
https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/

Manual intervention upon every releases can be avoided

**Comment by harshavardhana** [comment]
Providing write access from our repo to theirs is not going to work for us.

Automation is nice to have but they all want GitHub tokens which is a bad idea to automate.

Our project is sensitive to these things any exposure of tokens in CI/CD can break the project entirely.

Will add this as part of Goreleaser such that this can be done locally on a build system.
