### ISSUE TITLE
directcsi plugin not available in krew

### ISSUE THREAD

**Issue by bzakhar** [minio/direct-csi#69]
kubectl krew install directcsi
Updated the local copy of plugin index.
F1203 09:34:04.832111   19397 root.go:79] plugin "directcsi" does not exist in the plugin index

Is there a different index that needs to be added to krew? If yes - why is it not documented anywhere?

**Comment by wlan0** [comment]
Hi @bzakhar, We are just about to release our first version fo direct-csi. I'll ping you right here once that is done. You can expect a response from my early next week.

**Comment by bretagne-peiqi** [comment]
hi, I encountered the same situation, have  you released your version for krew install, thanks

**Comment by wlan0** [comment]
@bretagne-peiqi direct-csi v1.0.0 is now available on krew
